spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: springuser
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect